window.BNI_MEMBERS = [
  {
    id: "max-chan",
    name: "Max Chan",
    companyZh: "Mmatrix.io",
    companyEn: "Mmatrix.io",
    professionZh: "區塊鏈系統開發",
    professionEn: "Blockchain System Development",
    category: "it",
    introZh: "專注區塊鏈系統開發，包括受澳洲 Perth Mint 監管的代幣化黃金：每枚代幣 1:1 對應實體黃金，結合國家級背書與 Web3 流通性，協助客戶以合規方式持有及轉移數位資產。",
    introEn: "Builds blockchain systems including Perth Mint–regulated tokenised gold: each token is backed 1:1 by physical gold, combining government-grade custody with Web3 liquidity.",
    lookingForZh: ["需要合規數位黃金／資產配置的投資者", "關注 Web3 與實體資產代幣化的企業"],
    lookingForEn: ["Investors looking for compliant digital gold", "Businesses exploring tokenised real-world assets"],
    keywords: "blockchain crypto web3 區塊鏈 黃金 gold perth mint mmatrix.io"
  },
  {
    id: "larry-lo",
    name: "Larry Lo",
    companyZh: "InnovateXP Limited",
    companyEn: "InnovateXP Limited",
    professionZh: "AI 商業顧問",
    professionEn: "AI Business Consultant",
    category: "it",
    roleZh: "網絡統籌",
    roleEn: "Web Coordinator",
    introZh: "InnovateXP Limited 創辦人，提供人工智能商業顧問服務，協助企業把 AI 應用於營運、客戶體驗與增長策略。現任 BNI Anchor 網絡統籌。",
    introEn: "Founder of InnovateXP Limited. Advises businesses on putting AI to work in operations, customer experience and growth. Chapter web coordinator.",
    keywords: "AI 人工智能 顧問 innovatexp consultant technology"
  },
  {
    id: "jimmy-ho",
    name: "Jimmy Ho",
    companyZh: "Quick Time System",
    companyEn: "Quick Time System",
    professionZh: "POS 系統",
    professionEn: "POS Systems",
    category: "it",
    introZh: "Quick Time System 提供餐飲業管理系統、POS 及度身軟件設計，全年無休支援（09:00–22:30）。過往客戶包括太興、翠華、譚仔、銀龍及 Bar Pacific。",
    introEn: "Quick Time System builds F&B management systems, POS and tailored software, with support from 09:00–22:30 every day. Past clients include Tai Hing, Tsui Wah, TamJai, Noodle House and Bar Pacific.",
    lookingForZh: ["餐廳投資者", "各行業 IT 部主管"],
    lookingForEn: ["Restaurant investors", "IT leads across industries"],
    keywords: "POS 收銀 餐飲 restaurant 太興 翠華 譚仔 system"
  },
  {
    id: "johnny-li",
    name: "Johnny Li",
    companyZh: "",
    companyEn: "",
    professionZh: "會計及審計",
    professionEn: "Accounting & Audit",
    category: "professional",
    introZh: "提供會計及審計服務，協助企業整理帳目、符合合規要求，並以清晰的財務資訊支援決策。",
    introEn: "Provides accounting and audit services to help businesses keep clean books, stay compliant, and make decisions with clearer financial information.",
    keywords: "accounting audit CPA 會計 審計 核數"
  },
  {
    id: "leo-lam",
    name: "Leo Lam",
    companyZh: "Hive Personnel Limited",
    companyEn: "Hive Personnel Limited",
    professionZh: "外勞輸入",
    professionEn: "Foreign Worker Employment",
    category: "professional",
    introZh: "Hive Personnel Limited 專營外勞輸入，協助企業處理招聘、簽證及入境安排，為本地業務配對合適的海外人才。",
    introEn: "Hive Personnel Limited specialises in hiring foreign workers, supporting companies with recruitment, visas and immigration so the right talent can join local teams.",
    keywords: "外勞 輸入 僱傭 employment visa 簽證 人才 hive"
  },
  {
    id: "peter-chan",
    name: "Dr. Peter Chan",
    companyZh: "Mike So, Joseph Lau & Co",
    companyEn: "Mike So, Joseph Lau & Co",
    professionZh: "律師",
    professionEn: "Lawyer",
    category: "professional",
    introZh: "陳永洲律師，Mike So, Joseph Lau & Co 顧問律師。電子工程博士出身，2016 年成為執業律師。處理民事、家事及刑事訴訟，以及工傷、交通意外、醫療失誤、離婚、遺產承辦與樓宇買賣。",
    introEn: "Peter Chan (陳永洲), consultant solicitor at Mike So, Joseph Lau & Co. An electronics PhD who qualified in 2016. Handles civil, family and criminal litigation, plus injury, medical negligence, divorce, probate and conveyancing.",
    lookingForZh: ["需要訴訟或法律服務的當事人", "專科醫生、大律師、測量師、結構工程師等專家證人"],
    lookingForEn: ["People with legal disputes", "Expert witnesses: specialists, barristers, surveyors, structural engineers"],
    keywords: "lawyer solicitor 律師 陳永洲 訴訟 legal 家事 刑事"
  },
  {
    id: "ace-nau",
    name: "Ace Nau",
    companyZh: "Citybuild Interior Design",
    companyEn: "城投工程有限公司",
    professionZh: "室內設計及裝修",
    professionEn: "Interior Design & Renovation",
    category: "construction",
    introZh: "Citybuild 提供室內設計、裝修、除甲醛至 18 個月保養的一條龍服務，並訂造 0 甲醛全屋傢俬。師傅具備 15 年以上經驗，客戶包括廠房東主及美容院。",
    introEn: "Citybuild offers design, renovation, formaldehyde removal and 18-month aftercare, plus zero-formaldehyde custom furniture. Craftsmen have 15+ years’ experience with factory and salon clients.",
    lookingForZh: ["地產代理", "商場物業管理處／工程部", "商業顧問公司", "想打造 Dream House 的業主"],
    lookingForEn: ["Estate agents", "Mall property and engineering teams", "Business consultants", "Owners who want a dream home"],
    keywords: "interior design renovation 室內 裝修 citybuild 傢俬 construction"
  },
  {
    id: "joanne-chan",
    name: "Joanne Chan",
    companyZh: "Lazy Tech Co. Ltd.",
    companyEn: "Lazy Tech Co. Ltd.",
    professionZh: "商業及家居清潔",
    professionEn: "Commercial & Home Cleaning",
    category: "construction",
    introZh: "Lazy Tech 用心處理鎖碎而不顯眼的煩惱。恆常清潔覆蓋辦公室、24 小時健身中心、普拉提／瑜珈、私人會所、Studio、美容院、補習社及中西醫診所，亦提供除甲醛、裝修後清潔、空間消毒、洗地氈及滅蟲。",
    introEn: "Lazy Tech handles the unglamorous work that still matters: regular cleaning for offices, 24-hour gyms, pilates/yoga studios, clubs, beauty salons, tutorial centres and clinics, plus formaldehyde removal, post-renovation cleans, disinfection, carpet washing and pest control.",
    lookingForZh: ["需要恆常清潔的辦公室、健身中心、中西醫診所"],
    lookingForEn: ["Offices, gyms and clinics that need regular cleaning"],
    keywords: "cleaning 清潔 lazy gym 健身 家居 商業 除甲醛"
  },
  {
    id: "andrew-fong",
    name: "Andrew Fong",
    companyZh: "Team Richly Limited",
    companyEn: "Team Richly Limited",
    professionZh: "手錶買賣",
    professionEn: "Watch Trading",
    category: "lifestyle",
    roleZh: "活動統籌",
    roleEn: "Event Coordinator",
    introZh: "Team Richly Limited 從事手錶買賣，憑十多年鐘錶經驗為專業人士提供選錶、配套及維修方案。現任分會活動統籌。",
    introEn: "Team Richly Limited trades watches and, with more than a decade in the trade, helps clients choose, service and look after timepieces. Chapter event coordinator.",
    keywords: "watch 手錶 鐘錶 matchmaking richly luxury"
  },
  {
    id: "joe-li",
    name: "Joe Li",
    companyZh: "木木師傅",
    companyEn: "木木師傅",
    professionZh: "風水玄學",
    professionEn: "Feng Shui & Metaphysics",
    category: "lifestyle",
    introZh: "木木師傅提供風水玄學顧問服務，為家居、辦公室及商業選址提供布局建議，協助客戶營造更順心的生活與營商環境。",
    introEn: "木木師傅 advises on feng shui and metaphysics for homes, offices and business locations—helping clients shape spaces that support life and work.",
    keywords: "feng shui 風水 玄學 布局 metaphysics"
  },
  {
    id: "zoe-wu",
    name: "Zoe Wu",
    companyZh: "Zoe Floral",
    companyEn: "Zoe Floral",
    professionZh: "花藝師",
    professionEn: "Florist",
    category: "lifestyle",
    roleZh: "來賓接待",
    roleEn: "Visitor Host",
    introZh: "持荷蘭花藝師專業資格，亦曾赴韓國學習婚禮花藝。作品包括花束、餐廳佈置、開張花籃及婚禮花藝，客戶包括國際學校及家長會。現任來賓接待。",
    introEn: "A florist with Dutch professional credentials and wedding-floristry training in Korea. Creates bouquets, restaurant styling, opening baskets and wedding flowers. Chapter visitor host.",
    keywords: "florist flower 花 花藝 wedding 婚禮 zoe"
  },
  {
    id: "elva-cheung",
    name: "Elva Cheung",
    companyZh: "花貓仔追夢有限公司",
    companyEn: "花貓仔追夢有限公司",
    professionZh: "客製化歌曲訂製",
    professionEn: "Custom Song Commissioning",
    category: "lifestyle",
    introZh: "花貓仔追夢有限公司提供客製化歌曲創作，為求婚、婚禮、生日、品牌活動度身訂造音樂，把故事寫進旋律。",
    introEn: "花貓仔追夢有限公司 writes custom songs for proposals, weddings, birthdays and brand events—turning a story into music that lasts.",
    keywords: "song music 歌曲 訂製 音樂 wedding 客製"
  },
  {
    id: "phoebe-lin",
    name: "Phoebe Lin",
    companyZh: "MingMingEE Baby Care",
    companyEn: "MingMingEE Baby Care",
    professionZh: "催乳及紮肚服務",
    professionEn: "Lactation & Postpartum Binding",
    category: "lifestyle",
    introZh: "MingMingEE Baby Care 為產後媽媽提供催乳及紮肚服務，以專業護理支援哺乳與體質恢復，陪伴家庭渡過產後黃金期。",
    introEn: "MingMingEE Baby Care supports new mothers with lactation and postpartum binding, helping families through recovery and breastfeeding in the weeks after birth.",
    keywords: "lactation 催乳 紮肚 產後 baby postpartum 母嬰"
  },
  {
    id: "ryan-lau",
    name: "Ryan Lau",
    companyZh: "產前護膚安檢 App",
    companyEn: "Prenatal Skincare Check App",
    professionZh: "母嬰及兒童成長 App 研發",
    professionEn: "Maternal & Child Growth App Development",
    category: "lifestyle",
    introZh: "研發母嬰及兒童成長應用程式，以產前護膚安檢 App 協助準父母掌握護膚與健康資訊，用科技陪伴家庭成長每一步。",
    introEn: "Builds apps for maternal and child growth, including a prenatal skincare check app that helps expectant parents follow care and health information with more confidence.",
    keywords: "app 母嬰 兒童 產前 研發 developer pregnancy"
  },
  {
    id: "yoko-sin",
    name: "Yoko Sin",
    companyZh: "吉利旺有限公司",
    companyEn: "吉利旺有限公司",
    professionZh: "僱傭服務",
    professionEn: "Domestic Helper Services",
    category: "lifestyle",
    introZh: "吉利旺有限公司提供僱傭及職業介紹服務，協助家庭配對合適的家務助理，處理聘請、合約與日常支援。",
    introEn: "吉利旺有限公司 is an employment agency that matches households with domestic helpers and supports hiring, contracts and day-to-day needs.",
    keywords: "helper 僱傭 家務 外傭 maid agency 職業介紹"
  },
  {
    id: "jessica-cheung",
    name: "Jessica Cheung",
    companyZh: "MingMingEE Baby Care",
    companyEn: "MingMingEE Baby Care",
    professionZh: "陪月服務",
    professionEn: "Postpartum Confinement Care",
    category: "lifestyle",
    roleZh: "主席",
    roleEn: "President",
    gold: true,
    introZh: "MingMingEE Baby Care 提供專業陪月服務，為產後家庭安排貼心護理與起居支援。Jessica 為本屆分會主席，亦是金章會員。",
    introEn: "MingMingEE Baby Care provides professional postpartum confinement care for new families. Jessica is chapter president and a Gold Club member.",
    keywords: "陪月 confinement baby care president 主席 金章 gold"
  },
  {
    id: "hayes-lam",
    name: "Hayes Lam",
    companyZh: "Space Studio",
    companyEn: "Space Studio",
    professionZh: "品牌策劃",
    professionEn: "Brand Strategy",
    category: "marketing",
    introZh: "Space Studio 從事品牌策劃，協助企業梳理定位、視覺與傳播策略，讓品牌在市場上更清晰、更有記憶點。",
    introEn: "Space Studio works on brand strategy—helping companies clarify positioning, visuals and communications so the brand is easier to recognise and remember.",
    keywords: "branding brand 品牌 策劃 marketing studio"
  },
  {
    id: "one-chan",
    name: "One Chan",
    companyZh: "Chan One Photo",
    companyEn: "Chan One Photo",
    professionZh: "宣傳活動策劃及媒體公關",
    professionEn: "Event Promotion & Media PR",
    category: "marketing",
    introZh: "Chan One 專責宣傳活動策劃及媒體公關，為品牌設計活動體驗與媒體曝光，把故事送到對的觀眾面前。",
    introEn: "Chan One plans promotional events and media PR—designing experiences and coverage that put a brand story in front of the right audience.",
    keywords: "PR 公關 活動 宣傳 event media 攝影 photo"
  },
  {
    id: "stan-wang",
    name: "Stan Wang",
    companyZh: "台北人居酒屋 Taipei Izakaya",
    companyEn: "Taipei Izakaya",
    professionZh: "台式居酒屋",
    professionEn: "Taiwanese Izakaya",
    category: "fb",
    roleZh: "分會增長協調",
    roleEn: "Growth Coordinator",
    introZh: "台北人居酒屋位於佐敦，把台式料理結合居酒屋文化。Stan 擁有多年餐飲經驗，並持拿波里 Pizza 職人認證，現任分會增長協調。",
    introEn: "Taipei Izakaya in Jordan brings Taiwanese cooking together with izakaya culture. Stan has decades in F&B, holds Neapolitan pizza credentials, and serves as chapter growth coordinator.",
    keywords: "izakaya 居酒屋 台灣 餐飲 pizza 佐敦 restaurant"
  },
  {
    id: "ada-hau",
    name: "Ada Hau",
    companyZh: "Golden Long Food Trading Company Limited",
    companyEn: "Golden Long Food Trading Company Limited",
    professionZh: "食品代理及批發",
    professionEn: "Food Agency & Wholesale",
    category: "fb",
    introZh: "Golden Long Food Trading 從事食品代理及批發，為餐飲業及零售客戶供應食材與食品，協助餐廳穩定貨源。",
    introEn: "Golden Long Food Trading is a food agent and wholesaler, supplying ingredients and products to restaurants and retailers that need a steady source of goods.",
    keywords: "food wholesale 食品 代理 批發 trading F&B"
  },
  {
    id: "kevin-cheung",
    name: "Kevin Cheung",
    companyZh: "",
    companyEn: "",
    professionZh: "中式海鮮酒家",
    professionEn: "Chinese Seafood Restaurant",
    category: "fb",
    introZh: "經營中式海鮮酒家，為宴會、家庭聚餐及商務宴請提供新鮮海鮮與粵式菜式，講求出品與待客之道。",
    introEn: "Runs a Chinese seafood restaurant for banquets, family gatherings and business dinners—fresh seafood and Cantonese cooking with attentive hospitality.",
    keywords: "seafood 海鮮 酒家 中菜 restaurant 粵菜 banquet"
  },
  {
    id: "eric-ho",
    name: "Eric Ho",
    companyZh: "Nomader Consultancy Ltd",
    companyEn: "Nomader Consultancy Ltd",
    professionZh: "康體會所營運管理",
    professionEn: "Health Club Operations",
    category: "medical",
    introZh: "Nomader Consultancy 從事康體會所營運管理，服務多個健身品牌與分店投資者，涵蓋會籍、私人指導、場地營運及管理顧問。",
    introEn: "Nomader Consultancy manages health-club operations for gym brands and investors—memberships, personal training, venue operations and management advisory.",
    keywords: "gym fitness 健身 會所 營運 nomader snap"
  },
  {
    id: "wade-suen",
    name: "Dr. Wade Suen",
    companyZh: "InnoMeds",
    companyEn: "InnoMeds",
    professionZh: "港研健康產品",
    professionEn: "Hong Kong Health Products",
    category: "medical",
    introZh: "InnoMeds 研發及提供港研健康產品，以科研角度關注日常保健，協助客戶選擇適合自己的健康方案。",
    introEn: "InnoMeds develops Hong Kong health products, approaching everyday wellness with a research mindset and helping clients choose care that fits.",
    keywords: "health product 健康 產品 innomeds supplement 保健"
  },
  {
    id: "frankie-ng",
    name: "Frankie Ng",
    companyZh: "M&J Business Limited",
    companyEn: "M&J Business Limited",
    professionZh: "日經眼藥水及護眼素",
    professionEn: "Eye Drops & Eye Care",
    category: "medical",
    roleZh: "財務秘書",
    roleEn: "Treasurer",
    introZh: "M&J Business 代理日經眼藥水及護眼素，產品為香港衛生署登記中藥眼藥水，不含類固醇及防腐劑，關注糖尿病眼、黃斑及白內障護理。現任財務秘書。",
    introEn: "M&J Business supplies Japanese-formula eye drops and eye-care products registered with Hong Kong’s Department of Health as Chinese medicine, without steroids or preservatives. Chapter treasurer.",
    keywords: "eye 眼 眼藥水 護眼 cataract 白內障 treasurer 財務"
  },
  {
    id: "kate-woo",
    name: "Kate Woo",
    companyZh: "言醫坊",
    companyEn: "言醫坊",
    professionZh: "中醫",
    professionEn: "Chinese Medicine Practitioner",
    category: "medical",
    introZh: "香港註冊中醫師，言醫坊專注女性健康、身心平衡與自然養生。服務涵蓋婦科調理、情緒睡眠以及中醫美容。",
    introEn: "A Hong Kong registered Chinese-medicine practitioner at 言醫坊, focusing on women’s health, mind-body balance and natural care—including gynaecology, sleep, mood and TCM aesthetics.",
    keywords: "TCM 中醫 婦科 針灸 言醫坊 herbal"
  },
  {
    id: "ck-chow",
    name: "Dr. C.K. Chow",
    companyZh: "Brightmed Company Limited",
    companyEn: "Brightmed Company Limited",
    professionZh: "醫學美容",
    professionEn: "Medical Aesthetics",
    category: "medical",
    introZh: "家庭醫學專科醫生，於中環開設雅確皮膚中心（Brightmed），提供提升、收緊及美白等醫學美容療程。",
    introEn: "A specialist in family medicine. Runs Brightmed’s skin centre in Central, offering medical-aesthetic treatments for lifting, tightening and brightening.",
    keywords: "aesthetics 醫學美容 皮膚 brightmed 中環 doctor"
  },
  {
    id: "locus-lam",
    name: "Locus Lam",
    companyZh: "杏舘（社企）有限公司",
    companyEn: "杏舘（社企）有限公司",
    professionZh: "長者運動訓練",
    professionEn: "Elderly Exercise Training",
    category: "medical",
    introZh: "杏舘為社會企業，提供長者運動及體通能培訓，以安全、有系統的訓練幫助長者保持活動能力與生活質素。",
    introEn: "杏舘 is a social enterprise providing exercise and mobility training for older adults, using structured sessions to support movement and quality of life.",
    keywords: "elderly 長者 運動 社企 training mobility 體通能"
  },
  {
    id: "steves-tse",
    name: "Steves Tse",
    companyZh: "Sphere Island",
    companyEn: "Sphere Island",
    professionZh: "健身教練",
    professionEn: "Fitness Coach",
    category: "medical",
    introZh: "Sphere Island 健身教練，為個人及小組提供訓練計劃，協助學員建立力量、體能與可持續的運動習慣。",
    introEn: "A fitness coach at Sphere Island, designing personal and small-group training so clients build strength, conditioning and habits they can keep.",
    keywords: "fitness coach 健身 教練 trainer gym sphere"
  },
  {
    id: "ronnie-chan",
    name: "Dr Ronnie Chan",
    companyZh: "Gleneagles Pro-Heart Cardiac Centre",
    companyEn: "Gleneagles Pro-Heart Cardiac Centre",
    professionZh: "心臟科專科醫生",
    professionEn: "Specialist in Cardiology",
    category: "medical",
    introZh: "心臟科專科醫生，於 Gleneagles Pro-Heart Cardiac Centre 提供心臟檢查、診斷與專科治療，守護心臟健康。",
    introEn: "A cardiology specialist at Gleneagles Pro-Heart Cardiac Centre, providing heart assessments, diagnosis and specialist care.",
    keywords: "cardiology 心臟 專科 醫生 gleneagles heart"
  },
  {
    id: "gigi-liu",
    name: "Gigi Liu",
    companyZh: "",
    companyEn: "",
    professionZh: "日本小顏術",
    professionEn: "Japanese Facial Contouring",
    category: "medical",
    introZh: "提供日本小顏術服務，以非手術手法改善面部輪廓與線條，為客戶打造更立體、更精神的面相。",
    introEn: "Offers Japanese facial-contouring techniques that refine the face without surgery, helping clients achieve a more defined, refreshed look.",
    keywords: "小顏 面部 美容 facial contouring japan 日本"
  },
  {
    id: "enoch-hung",
    name: "Enoch Hung",
    companyZh: "Physio Memoir",
    companyEn: "Physio Memoir",
    professionZh: "物理治療師",
    professionEn: "Physiotherapist",
    category: "medical",
    introZh: "註冊物理治療師，Physio Memoir 處理運動創傷及痛症。曾服務港隊運動員、Hyrox 選手以至社區街坊，目標是「少一點疼痛，多一點生活」。",
    introEn: "A registered physiotherapist at Physio Memoir treating sports injuries and pain. Has worked with Hong Kong team athletes, Hyrox competitors and everyday clients—less pain, more life.",
    keywords: "physio 物理治療 痛症 injury 運動 sports"
  },
  {
    id: "vincent-chung",
    name: "Vincent Chung",
    companyZh: "EH Medical Group 恆健香港醫療顧問有限公司",
    companyEn: "EH Medical Group",
    professionZh: "專科醫療中心",
    professionEn: "Specialty Medical Centre",
    category: "medical",
    introZh: "EH Medical Group（恆健香港醫療顧問有限公司）營運專科醫療中心，為病人提供專科診治及醫療顧問服務。",
    introEn: "EH Medical Group operates a specialty medical centre, offering specialist care and medical advisory services for patients who need focused treatment.",
    keywords: "medical 醫療 專科 診所 EH 恆健 hospital"
  },
  {
    id: "rebecca-hung",
    name: "Rebecca Hung",
    companyZh: "World Family",
    companyEn: "World Family",
    professionZh: "兒童英語",
    professionEn: "Children's English",
    category: "education",
    introZh: "World Family 提供兒童英語教育，以有趣、有系統的課程幫助小朋友建立聽講讀寫能力與學習自信。",
    introEn: "World Family teaches English to children through structured, engaging lessons that build listening, speaking, reading, writing and confidence.",
    keywords: "English 英語 兒童 教育 tutor kids world family"
  },
  {
    id: "bill-chung",
    name: "Bill Chung",
    companyZh: "BOC Life",
    companyEn: "BOC Life",
    professionZh: "銀行服務",
    professionEn: "Banking Services",
    category: "finance",
    introZh: "任職中銀集團人壽（BOC Life），提供銀行及人壽保障相關服務，協助客戶處理財富規劃與保障需要。",
    introEn: "Works with BOC Life on banking and life-protection services, helping clients with wealth planning and insurance needs.",
    keywords: "bank 銀行 BOC 中銀 life 人壽 banking"
  },
  {
    id: "raymond-kuo",
    name: "Raymond Kuo",
    companyZh: "AIA International Ltd",
    companyEn: "AIA International Ltd",
    professionZh: "個人保險（理財及儲蓄）",
    professionEn: "Personal Insurance (Wealth & Savings)",
    category: "finance",
    roleZh: "教育統籌",
    roleEn: "Education Coordinator",
    introZh: "友邦保險顧問，專注個人理財、儲蓄及保障策劃，為家庭與企業客戶提供一站式財富管理。百萬圓桌會終身會員，現任分會教育統籌。",
    introEn: "An AIA advisor focused on personal wealth, savings and protection. Offers one-stop planning for families and business owners. MDRT life member and chapter education coordinator.",
    keywords: "AIA 保險 insurance MDRT 理財 儲蓄 教育"
  },
  {
    id: "li-ka-wai",
    name: "Li Ka Wai",
    companyZh: "妃蓍安老服務有限公司",
    companyEn: "妃蓍安老服務有限公司",
    professionZh: "一般保險",
    professionEn: "General Insurance",
    category: "finance",
    introZh: "妃蓍安老服務有限公司提供一般保險服務，為個人及企業處理財產、責任及日常風險保障。",
    introEn: "妃蓍安老服務有限公司 provides general insurance for individuals and businesses—covering property, liability and everyday risk.",
    keywords: "general insurance 一般保險 安老 財產 責任"
  },
  {
    id: "cyrus-koo",
    name: "Cyrus Koo",
    companyZh: "YF Life Insurance International Limited",
    companyEn: "YF Life Insurance International Limited",
    professionZh: "個人保險（健康及保障）",
    professionEn: "Personal Insurance (Health & Protection)",
    category: "finance",
    roleZh: "新會員輔導",
    roleEn: "Mentor Coordinator",
    introZh: "萬通保險顧問，專注個人健康及保障。入行多年，處理過大量理賠個案，強調 24/7 可靠服務。現任新會員輔導。",
    introEn: "A YF Life advisor focused on personal health and protection. Known for responsive, reliable service and claims support. Chapter mentor coordinator for new members.",
    keywords: "YF 萬通 insurance 保險 健康 保障 mentor 輔導"
  },
  {
    id: "richard-wong",
    name: "Richard Wong",
    companyZh: "AIA",
    companyEn: "AIA",
    professionZh: "強積金",
    professionEn: "MPF",
    category: "finance",
    roleZh: "副主席",
    roleEn: "Vice President",
    introZh: "友邦保險顧問，專注強積金策劃，服務初創至中型企業僱主及僱員。現任分會副主席。",
    introEn: "An AIA advisor specialising in MPF planning for start-up and mid-size employers and their staff. Chapter vice president.",
    keywords: "MPF 強積金 AIA 保險 vice president 副主席"
  }
];

window.BNI_CATEGORIES = [
  {
    id: "it",
    zh: "資訊及創新科技",
    en: "Information Technology",
    color: "#c8102e"
  },
  {
    id: "professional",
    zh: "專業及企業服務",
    en: "Professional & Corporate Services",
    color: "#e36b1e"
  },
  {
    id: "construction",
    zh: "建築工程及環境衛生",
    en: "Construction & Engineering",
    color: "#c4a035"
  },
  {
    id: "lifestyle",
    zh: "生活品味及家庭服務",
    en: "Lifestyle & Family Services",
    color: "#2f9b6e"
  },
  {
    id: "marketing",
    zh: "市場推廣及展覽",
    en: "Marketing & Exhibition",
    color: "#5a8f3a"
  },
  {
    id: "fb",
    zh: "食品及餐飲",
    en: "Food & Beverage",
    color: "#1a9bb0"
  },
  {
    id: "medical",
    zh: "醫療、健康及運動",
    en: "Medical, Health & Sports",
    color: "#2f5fa8"
  },
  {
    id: "education",
    zh: "教育及培訓",
    en: "Education & Training",
    color: "#c44c3a"
  },
  {
    id: "finance",
    zh: "金融、投資及地產",
    en: "Finance, Investment & Property",
    color: "#6b3d91"
  }
];
