services:
  - type: web
    runtime: static
    name: bni-anchor-website
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /images/*
        name: Cache-Control
        value: public, max-age=604800
      - path: /css/*
        name: Cache-Control
        value: public, max-age=86400
      - path: /js/*
        name: Cache-Control
        value: public, max-age=86400
